import React, { createContext, useState, useContext, ReactNode } from 'react';

type Language = 'es' | 'en';

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const translations = {
  es: {
    'nav.book': 'Agendar Consulta',
    'banner.urgency': 'Capacidad limitada: 5 proyectos mensuales. Reserva hoy tu auditoría de diagnóstico para asegurar tu cupo de Julio.',
    'hero.badge': 'TRÁFICO + CONVERSIÓN AUTOMÁTICA B2B',
    'hero.title1': 'El sistema definitivo para escalar ',
    'hero.title2': 'tu negocio digitalmente',
    'hero.subtitle': 'Creamos anuncios estratégicos en Meta Ads que multiplican tus visualizaciones e implementamos ecosistemas automatizados que convierten ese tráfico en facturación real en tu negocio.',
    'hero.cta': 'Solicitar diagnóstico gratuito',
    
    'workflow.meta.title': 'ANUNCIOS META ADS',
    'workflow.meta.sub': 'CONVERSIONES AUTOMÁTICAS',
    'workflow.landing.title': 'LANDING PAGE',
    'workflow.landing.sub': 'CAPTACIÓN',
    'workflow.landing.system': 'TU SISTEMA',
    'workflow.landing.contact': 'Contactar',
    'workflow.whatsapp.title': 'WHATSAPP',
    'workflow.whatsapp.sub': 'CHATBOT 24/7',
    'workflow.whatsapp.bot': 'Bot IA',
    'workflow.whatsapp.msg1': '¡Hola! ¿En qué te ayudo?',
    'workflow.whatsapp.msg2': 'Más info.',
    'workflow.whatsapp.msg3': '¡Claro! ¿Agendamos?',
    'workflow.calendar.title': 'REUNIÓN CONFIRMADA',
    'workflow.calendar.sub': 'RESERVA AUTOMÁTICA',
    'workflow.calendar.date': '13 MARZO',
    'workflow.calendar.demo': 'DEMO DE SISTEMA',

    'problem.title': '¿Por qué estás perdiendo clientes todos los días?',
    'problem.subtitle': 'El problema es la falta de un ecosistema que conecte los anuncios de Meta con la conversión.',
    'problem.1.title': 'Invisibilidad en Instagram',
    'problem.1.desc': 'Marcas estancadas publicando contenido que nadie ve por no aprovechar Meta Ads estratégicamente.',
    'problem.2.title': 'Respuestas Lentas',
    'problem.2.desc': 'Recibes mensajes por anuncios pero tu equipo tarda en responder, enfriando al lead y perdiendo ventas.',
    'problem.3.title': 'Web Fantasma',
    'problem.3.desc': 'Tienes un sitio hermoso o e-commerce que no recibe tráfico calificado y no genera ventas.',
    'problem.4.title': 'Presupuesto Quemado',
    'problem.4.desc': 'Haces campañas sin un embudo automatizado detrás, quemando el dinero invertido en Meta Ads.',

    'solution.title1': 'El Ecosistema de ',
    'solution.title2': 'Crecimiento Acelerado',
    'solution.subtitle': 'Implementamos un flujo continuo que multiplica tu visibilidad, automatiza tus conversaciones y convierte desconocidos en ventas reales en tu sitio web.',
    'solution.1.label': 'ANUNCIOS DE META ADS',
    'solution.1.sub': 'Visibilidad e impacto en Instagram para atraer a tu cliente ideal todos los días.',
    'solution.2.label': 'MENSAJES Y CHATBOTS',
    'solution.2.sub': 'Automatización conversacional 24/7 para responder al instante y calificar cada oportunidad.',
    'solution.3.label': 'TU SITIO WEB O LANDING',
    'solution.3.sub': 'Tráfico ultra-cualificado directo a tus páginas de producto o servicios para maximizar la conversión.',
    'solution.4.label': 'VENTA O CLIENTE CERRADO',
    'solution.4.sub': 'Cierre de facturación fluido y automático, directo a tu cuenta sin esfuerzo operativo.',

    'pricing.title1': 'Ecosistema de ',
    'pricing.title2': 'Crecimiento',
    'pricing.subtitle': 'Soluciones integrales para escalar tu captación de clientes.',
    'pricing.basic.title': 'Plan Tráfico',
    'pricing.basic.desc': 'Ideal para marcas que buscan visibilidad, tráfico y dominar el algoritmo.',
    'pricing.pro.badge': 'Más Elegido',
    'pricing.pro.title': 'Plan Profesional',
    'pricing.pro.desc': 'Para empresas que buscan anuncios de alto impacto combinados con respuestas instantáneas.',
    'pricing.full.title': 'Plan Completo',
    'pricing.full.desc': 'El sistema definitivo de crecimiento: Tráfico masivo y automatización de punta a punta.',
    'pricing.basic.1': 'Diseño y edición de anuncios (imágenes y/o videos)',
    'pricing.basic.2': 'Configuración estratégica de campañas',
    'pricing.basic.3': 'Creación y segmentación de públicos',
    'pricing.basic.4': 'Monitorización diaria de campañas',
    'pricing.basic.5': 'Análisis de KPI\'s para mejorar el rendimiento',
    'pricing.pro.1': 'Todo lo del plan anterior (Meta Ads Avanzado)',
    'pricing.pro.2': 'WhatsApp con IA integrada',
    'pricing.pro.3': 'Calificación automática de prospectos',
    'pricing.pro.4': 'Estructura de Landing Page optimizada',
    'pricing.pro.5': 'Conexión con Agenda automatizada',
    'pricing.pro.6': 'Recordatorios automáticos para citas/ventas',
    'pricing.pro.7': 'Soporte Técnico especializado',
    'pricing.pro.8': 'Requiere Verificación de Meta',
    'pricing.full.1': 'Estrategia Omnicanal de Meta Ads',
    'pricing.full.2': 'WhatsApp con IA Avanzada y flujos personalizados',
    'pricing.full.3': 'Calificación y segmentación automática en Base de Datos',
    'pricing.full.4': 'Landing Page / Embudo de conversión Premium',
    'pricing.full.5': 'Conexión avanzada con Agenda y CRM del cliente',
    'pricing.full.6': 'Sistema automatizado de Recordatorios y Seguimiento',
    'pricing.full.7': 'Capacitación completa al equipo del cliente',
    'pricing.full.8': 'Soporte Técnico prioritario y optimización mensual',
    'pricing.full.9': 'Requiere Verificación de Meta',
    'pricing.btn': 'Elegir Plan',
    'pricing.implementation': 'Implementación (pago único)',
    'pricing.opt.basic': 'Optimización mensual (-20%)',
    'pricing.opt.pro': 'Optimización mensual (-30%)',
    'pricing.opt.full': 'Optimización mensual incluida',
    'pricing.opt.note': 'La optimización mensual está pensada para mejorar resultados y rendimiento.',

    'how.title': '¿Cómo funciona?',
    'how.subtitle': 'Un proceso simple y transparente para transformar tu captación de clientes.',
    'how.1.title': 'Analizamos tu negocio',
    'how.1.desc': 'Entendemos tu proceso de ventas actual y detectamos cuellos de botella.',
    'how.2.title': 'Diseñamos el sistema',
    'how.2.desc': 'Creamos la estrategia de captación y el flujo de conversación ideal.',
    'how.3.title': 'Automatizamos',
    'how.3.desc': 'Implementamos el bot de WhatsApp, la IA y conectamos tu agenda.',
    'how.4.title': 'Recibes consultas',
    'how.4.desc': 'Tu empresa empieza a recibir turnos y consultas calificadas automáticamente.',

    'target.title': 'Para quién es este servicio',
    'target.subtitle': 'Nuestra solución está diseñada para empresas de servicios que dependen de la agendación de citas y la atención rápida al cliente.',
    'target.i1': 'Clínicas y Consultorios',
    'target.i2': 'Inmobiliarias',
    'target.i3': 'Abogados y Estudios',
    'target.i4': 'Consultores B2B',
    'target.i5': 'Academias y Formación',
    'target.i6': 'Servicios para el Hogar',
    'target.c1.title': 'Nuevo turno agendado',
    'target.c1.time': 'Hace 2 minutos',
    'target.c2.title': 'Consulta respondida por IA',
    'target.c2.time': 'Hace 5 minutos',
    'target.c3.title': 'Recordatorio enviado',
    'target.c3.time': 'Hace 15 minutos',

    'trust.badge': 'Política de transparencia',
    'trust.title': 'Propiedad total para el cliente',
    'trust.1': 'Las cuentas siempre quedan a nombre del cliente',
    'trust.2': 'El sistema sigue funcionando incluso si cancelas el mantenimiento',
    'trust.3': 'Sin contratos de permanencia',
    'trust.quote': '"Trabajamos para que te quedes por el valor que entregamos, no por obligación."',

    'contact.success.title': '¡Gracias por tu interés!',
    'contact.success.d1': 'Serás redirigido a nuestro WhatsApp.',
    'contact.success.d2': 'Allí podremos coordinar tu diagnóstico gratuito.',
    'contact.success.btn': 'Volver al formulario',
    'contact.success.pdf': 'Descargar PDF informativo',
    'contact.whatsapp.msg': 'Hola, quiero más información',
    'contact.title': 'Agenda una auditoría GRATIS de 20 minutos',
    'contact.subtitle': '',
    'contact.label.name': 'Nombre Responsable',
    'contact.placeholder.name': 'Ej. Juan Pérez',
    'contact.label.service': 'El servicio que necesito es:',
    'contact.opt.basic': 'Plan Tráfico',
    'contact.opt.pro': 'Plan Profesional',
    'contact.opt.full': 'Plan Completo',
    'contact.opt.unsure': 'No estoy seguro, necesito asesoría',
    'contact.btn': 'Agendar Gratis por WhatsApp',
    'contact.note': 'Serás redirigido a nuestro WhatsApp para coordinar la reunión.',

    'footer.home': 'Inicio',
    'footer.pricing': 'Precios',
    'footer.contact': 'Contacto',
    'footer.copy1': '© 2024 Sinergia Digital - Líderes en Automatización de Captación.',
    'footer.copy2': 'Transformando prospectos en clientes mediante inteligencia artificial.'
  },
  en: {
    'nav.book': 'Book Consultation',
    'banner.urgency': 'Limited capacity: 5 projects per month. Book your diagnostic audit today to secure your spot for July.',
    'hero.badge': 'TRAFFIC + AUTOMATIC B2B CONVERSION',
    'hero.title1': 'The ultimate system to scale ',
    'hero.title2': 'your business digitally',
    'hero.subtitle': 'We create strategic Meta Ads that multiply your views and implement automated ecosystems that convert that traffic into real revenue for your business.',
    'hero.cta': 'Request free diagnosis',

    'workflow.meta.title': 'META ADS CAMPAIGNS',
    'workflow.meta.sub': 'AUTOMATIC CONVERSIONS',
    'workflow.landing.title': 'LANDING PAGE',
    'workflow.landing.sub': 'LEAD CAPTURE',
    'workflow.landing.system': 'YOUR SYSTEM',
    'workflow.landing.contact': 'Contact',
    'workflow.whatsapp.title': 'WHATSAPP',
    'workflow.whatsapp.sub': '24/7 CHATBOT',
    'workflow.whatsapp.bot': 'AI Bot',
    'workflow.whatsapp.msg1': 'Hi! How can I help?',
    'workflow.whatsapp.msg2': 'More info.',
    'workflow.whatsapp.msg3': 'Sure! Shall we book?',
    'workflow.calendar.title': 'CONFIRMED MEETING',
    'workflow.calendar.sub': 'AUTOMATIC BOOKING',
    'workflow.calendar.date': 'MARCH 13',
    'workflow.calendar.demo': 'SYSTEM DEMO',

    'problem.title': 'Why are you losing clients every day?',
    'problem.subtitle': 'The problem is the lack of an ecosystem that connects Meta Ads with actual conversion.',
    'problem.1.title': 'Invisibility on Instagram',
    'problem.1.desc': 'Stagnant brands posting content nobody sees due to not leveraging Meta Ads strategically.',
    'problem.2.title': 'Slow Responses',
    'problem.2.desc': 'You receive messages from ads but your team takes too long to reply, cooling leads and losing sales.',
    'problem.3.title': 'Ghost Website',
    'problem.3.desc': 'You have a beautiful website or e-commerce that doesn\'t receive qualified traffic and generates no sales.',
    'problem.4.title': 'Wasted Budget',
    'problem.4.desc': 'You run campaigns without an automated funnel behind them, burning the money invested in Meta Ads.',

    'solution.title1': 'The Accelerated ',
    'solution.title2': 'Growth Ecosystem',
    'solution.subtitle': 'We implement a continuous flow that multiplies your visibility, automates your conversations, and turns strangers into real sales on your website.',
    'solution.1.label': 'META ADS',
    'solution.1.sub': 'Visibility and impact on Instagram to attract your ideal client every day.',
    'solution.2.label': 'MESSAGES & CHATBOTS',
    'solution.2.sub': '24/7 conversational automation to respond instantly and qualify every opportunity.',
    'solution.3.label': 'YOUR WEBSITE OR LANDING',
    'solution.3.sub': 'Ultra-qualified traffic direct to your product or service pages to maximize conversion.',
    'solution.4.label': 'SALE OR CLOSED CLIENT',
    'solution.4.sub': 'Smooth and automatic billing closure, direct to your account without operational effort.',

    'pricing.title1': 'Growth ',
    'pricing.title2': 'Ecosystem',
    'pricing.subtitle': 'Comprehensive scalable solutions for every stage of your business.',
    'pricing.basic.title': 'Traffic Plan',
    'pricing.basic.desc': 'Ideal for brands looking for visibility, traffic and dominating the algorithm.',
    'pricing.pro.badge': 'Most Popular',
    'pricing.pro.title': 'Professional Plan',
    'pricing.pro.desc': 'For companies looking for high-impact ads combined with instant responses.',
    'pricing.full.title': 'Complete Plan',
    'pricing.full.desc': 'The ultimate growth system: Massive traffic and end-to-end automation.',
    'pricing.basic.1': 'Ad design and editing (Image and video editing)',
    'pricing.basic.2': 'Strategic campaign configuration',
    'pricing.basic.3': 'Audience creation and segmentation',
    'pricing.basic.4': 'Daily campaign monitoring',
    'pricing.basic.5': 'KPI analysis to improve performance',
    'pricing.pro.1': 'Everything in the previous plan (Advanced Meta Ads)',
    'pricing.pro.2': 'AI integrated WhatsApp',
    'pricing.pro.3': 'Automatic lead qualification',
    'pricing.pro.4': 'Landing Page structure optimized for conversion',
    'pricing.pro.5': 'Automated Calendar Connection',
    'pricing.pro.6': 'Automatic reminders for meetings/sales',
    'pricing.pro.7': 'Specialized Technical Support',
    'pricing.pro.8': 'Requires Meta Verification',
    'pricing.full.1': 'Omnichannel Meta Ads Strategy',
    'pricing.full.2': 'Advanced AI WhatsApp with custom flows',
    'pricing.full.3': 'Automatic Database Qualification and Segmentation',
    'pricing.full.4': 'Premium Landing Page / Conversion Funnel',
    'pricing.full.5': 'Advanced connection with client Agenda and CRM',
    'pricing.full.6': 'Automated Follow-up and Reminders system',
    'pricing.full.7': 'Complete client team training',
    'pricing.full.8': 'Priority Technical Support and monthly optimization',
    'pricing.full.9': 'Requires Meta Verification',
    'pricing.btn': 'Choose Plan',
    'pricing.implementation': 'Implementation (one-time payment)',
    'pricing.opt.basic': 'Monthly optimization (-20%)',
    'pricing.opt.pro': 'Monthly optimization (-30%)',
    'pricing.opt.full': 'Monthly Optimization included in plan',
    'pricing.opt.note': 'Monthly optimization is designed to improve results and performance.',

    'how.title': 'How does it work?',
    'how.subtitle': 'A simple and transparent process to transform your client acquisition.',
    'how.1.title': 'We analyze your business',
    'how.1.desc': 'We understand your current sales process and detect bottlenecks.',
    'how.2.title': 'We design the system',
    'how.2.desc': 'We create the capture strategy and the ideal conversation flow.',
    'how.3.title': 'We automate',
    'how.3.desc': 'We implement the WhatsApp bot, AI, and connect your calendar.',
    'how.4.title': 'You receive inquiries',
    'how.4.desc': 'Your company starts receiving appointments and qualified inquiries automatically.',

    'target.title': 'Who is this service for',
    'target.subtitle': 'Our solution is designed for service companies that rely on appointment scheduling and fast customer service.',
    'target.i1': 'Clinics and Practices',
    'target.i2': 'Real Estate',
    'target.i3': 'Lawyers and Firms',
    'target.i4': 'B2B Consultants',
    'target.i5': 'Academies and Training',
    'target.i6': 'Home Services',
    'target.c1.title': 'New appointment booked',
    'target.c1.time': '2 minutes ago',
    'target.c2.title': 'Inquiry answered by AI',
    'target.c2.time': '5 minutes ago',
    'target.c3.title': 'Reminder sent',
    'target.c3.time': '15 minutes ago',

    'trust.badge': 'Transparency Policy',
    'trust.title': 'Full ownership for the client',
    'trust.1': 'Accounts always remain in the client\'s name',
    'trust.2': 'The system keeps working even if you cancel maintenance',
    'trust.3': 'No lock-in contracts',
    'trust.quote': '"We work so you stay for the value we deliver, not out of obligation."',

    'contact.success.title': 'Thank you for your interest!',
    'contact.success.d1': 'You will be redirected to our WhatsApp.',
    'contact.success.d2': 'There we can coordinate your free diagnosis.',
    'contact.success.btn': 'Back to form',
    'contact.success.pdf': 'Download Info PDF',
    'contact.whatsapp.msg': 'Hi, I want more information.',
    'contact.title': 'Schedule a FREE 20-minute audit',
    'contact.subtitle': '',
    'contact.label.name': 'Manager Name',
    'contact.placeholder.name': 'E.g. John Doe',
    'contact.label.service': 'The service I need is:',
    'contact.opt.basic': 'Traffic Plan',
    'contact.opt.pro': 'Professional Plan',
    'contact.opt.full': 'Complete Plan',
    'contact.opt.unsure': 'I am not sure, I need advice',
    'contact.btn': 'Schedule Free via WhatsApp',
    'contact.note': 'You will be redirected to our WhatsApp to coordinate the meeting.',

    'footer.home': 'Home',
    'footer.pricing': 'Pricing',
    'footer.contact': 'Contact',
    'footer.copy1': '© 2024 Sinergia Digital - Leaders in Acquisition Automation.',
    'footer.copy2': 'Transforming prospects into clients through artificial intelligence.'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('es');

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'es' ? 'en' : 'es');
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['es']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
